// apps/nuxt-example/components/TransactonFlows/SingleSigner.vue
<script setup lang="ts">
import { computed, h } from "vue";
import { movementClient, isSendableNetwork } from "@/utils";
import { AccountAddress, parseTypeTag, U64 } from "@movement-labs/ts-sdk";
import { InputTransactionData } from "@movement-labs/wallet-adapter-core";
import TransactionHash from "~/components/TransactionHash.vue";
import { useToast } from "~/components/ui/toast";
const { toast } = useToast();
const { $walletAdapter } = useNuxtApp();
const {
  network,
  connected,
  account,
  signAndSubmitTransaction,
  signMessageAndVerify,
  signMessage,
  signTransaction,
} = $walletAdapter;

const MOVEMENT_COIN = "0x1::aptos_coin::AptosCoin";

const isSendable = computed(() =>
  isSendableNetwork(connected.value, network.value?.name || undefined),
);

const onSignMessageAndVerify = async () => {
  const payload = {
    message: "Hello from Movement Wallet Adapter",
    nonce: Math.random().toString(16),
  };
  const response = await signMessageAndVerify(payload);
  toast({
    title: "Success",
    description: JSON.stringify({ onSignMessageAndVerify: response }),
  });
};

const onSignMessage = async () => {
  const payload = {
    message: "Hello from Movement Wallet Adapter",
    nonce: Math.random().toString(16),
  };
  const response = await signMessage(payload);
  toast({
    title: "Success",
    description: JSON.stringify({ onSignMessage: response }),
  });
};

const onSignAndSubmitTransaction = async () => {
  if (!account) return;
  const transaction: InputTransactionData = {
    data: {
      function: "0x1::coin::transfer",
      typeArguments: [MOVEMENT_COIN],
      functionArguments: [account.value?.address.toString(), 1], // 1 is in Octas
    },
  };
  try {
    const response = await signAndSubmitTransaction(transaction);
    await movementClient(network.value).waitForTransaction({
      transactionHash: response.hash,
    });
    toast({
      title: "Success",
      description: h(TransactionHash, {
        hash: response.hash,
        network: network.value,
      }),
    });
  } catch (error) {
    console.error(error);
  }
};

const onSignAndSubmitBCSTransaction = async () => {
  if (!account.value) return;

  try {
    const response = await signAndSubmitTransaction({
      data: {
        function: "0x1::coin::transfer",
        typeArguments: [parseTypeTag(MOVEMENT_COIN)],
        functionArguments: [
          AccountAddress.from(account.value?.address),
          new U64(1),
        ], // 1 is in Octas
      },
    });
    await movementClient(network.value).waitForTransaction({
      transactionHash: response.hash,
    });
    toast({
      title: "Success",
      description: h(TransactionHash, {
        hash: response.hash,
        network: network.value,
      }),
    });
  } catch (error) {
    console.error(error);
  }
};

// Legacy typescript sdk support
const onSignTransaction = async () => {
  try {
    const payload = {
      type: "entry_function_payload",
      function: "0x1::coin::transfer",
      type_arguments: ["0x1::aptos_coin::AptosCoin"],
      arguments: [account.value?.address.toString(), 1], // 1 is in Octas
    };
    const response = await signTransaction(payload);
    toast({
      title: "Success",
      description: JSON.stringify(response),
    });
  } catch (error) {
    console.error(error);
  }
};

const onSignTransactionV2 = async () => {
  if (!account.value) return;

  try {
    const transactionToSign = await movementClient(
      network.value,
    ).transaction.build.simple({
      sender: account.value?.address,
      data: {
        function: "0x1::coin::transfer",
        typeArguments: [MOVEMENT_COIN],
        functionArguments: [account.value?.address.toString(), 1], // 1 is in Octas
      },
    });
    const response = await signTransaction(transactionToSign);
    toast({
      title: "Success",
      description: JSON.stringify(response),
    });
  } catch (error) {
    console.error(error);
  }
};
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Single Signer Flow</CardTitle>
    </CardHeader>
    <CardContent class="flex flex-wrap gap-4">
      <Button @click="onSignAndSubmitTransaction" :disabled="!isSendable">
        Sign and submit transaction
      </Button>
      <Button @click="onSignAndSubmitBCSTransaction" :disabled="!isSendable">
        Sign and submit BCS transaction
      </Button>
      <Button @click="onSignTransaction" :disabled="!isSendable">
        Sign transaction
      </Button>
      <Button @click="onSignTransactionV2" :disabled="!isSendable">
        Sign transaction V2
      </Button>
      <Button @click="onSignMessage" :disabled="!isSendable">
        Sign message
      </Button>
      <Button @click="onSignMessageAndVerify" :disabled="!isSendable">
        Sign message and verify
      </Button>
    </CardContent>
  </Card>
</template>

// apps/nextjs-x-chain/src/components/transactionFlows/SingleSigner.tsx
import { getAptBalanceQueryOptions } from "@/utils/getAptBalanceQueryOptions";
import {
  Account,
  AccountAuthenticator,
  Ed25519PrivateKey,
  InputGenerateTransactionPayloadData,
  Network,
  PrivateKey,
  PrivateKeyVariants,
} from "@movement-labs/ts-sdk";
import {
  InputTransactionData,
  useWallet,
  AdapterWallet,
} from "@movement-labs/wallet-adapter-react";

import { isSendableNetwork, movementClient } from "@/utils";
import { useQuery } from "@tanstack/react-query";
import { Button } from "../ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "../ui/card";
import { useToast } from "../ui/use-toast";
import { TransactionHash } from "../TransactionHash";
import { useUSDCBalance } from "@/contexts/USDCBalanceContext";
import { getTransactionSubmitter } from "@/utils/transactionSubmitter";

/**
 * Generate a nonce with alphanumeric characters only.
 * This is a requirement for Sign in With Solana nonces
 */
function generateNonce() {
  return crypto.randomUUID().replaceAll("-", "");
}

export type SingleSignerProps = {
  dappNetwork: Network;
  wallet: AdapterWallet;
};

export function SingleSigner({ dappNetwork, wallet }: SingleSignerProps) {
  const { toast } = useToast();
  const {
    connected,
    account,
    network,
    signMessageAndVerify,
    signMessage,
    signTransaction,
    signAndSubmitTransaction,
  } = useWallet();
  const { globalTransactionInProgress, setGlobalTransactionInProgress } =
    useUSDCBalance();

  let sendable = isSendableNetwork(connected, network?.name);

  const onSignMessageAndVerify = async () => {
    if (!account) return;
    try {
      const payload = {
        message: "Hello from Movement Wallet Adapter",
        nonce: generateNonce(),
      };
      const response = await signMessageAndVerify(payload);
      console.log("sign message and verify response", response);
      toast({
        title: "Success",
        description: JSON.stringify({ onSignMessageAndVerify: response }),
      });
    } catch (error) {
      console.error(error);
      toast({
        title: "Error",
        description: `${error}`,
      });
    }
  };

  const onSignMessage = async () => {
    if (!account) return;
    try {
      const payload = {
        message: "Hello from Movement Wallet Adapter",
        nonce: generateNonce(),
      };
      const response = await signMessage(payload);
      console.log("sign message response", response);
      toast({
        title: "Success",
        description: JSON.stringify({ onSignMessage: response }),
      });
    } catch (error) {
      console.error(error);
      toast({
        title: "Error",
        description: `${error}`,
      });
    }
  };

  const onSignTransaction = async () => {
    try {
      if (!account) return;
      const payload: InputTransactionData = {
        data: {
          function: "0x1::aptos_account::transfer",
          functionArguments: [account.address, 1],
        },
        withFeePayer: true,
      };
      const response = await signTransaction({
        transactionOrPayload: payload,
      });
      console.log("sign transaction response", response);
      toast({
        title: "Success",
        description: JSON.stringify(response),
      });
    } catch (error) {
      console.error(error);
      toast({
        title: "Error",
        description: `${error}`,
      });
    }
  };

  const aptBalance = useQuery({
    enabled: account !== undefined && network !== undefined,
    ...getAptBalanceQueryOptions({
      accountAddress: account!.address,
      network: network!.name,
    }),
  });

  const onSignAndSubmitTransaction = async () => {
    if (!account) return;

    let transactionData: InputGenerateTransactionPayloadData;

    // On testnet, derived account can't just fund their account with APT on the UI (but need to go to the faucet to get APT),
    // we will post a message to the message board as an example.
    // We can guarantee that the message board is deployed on Testnet as it is not getting wiped (like devnet).
    if (dappNetwork === Network.TESTNET) {
      transactionData = {
        function:
          "0xeadc81e5ac02adc11308f643761294e27103a4a36822761633fd40cb08f59ed9::message_board::post_message",
        functionArguments: ["Hello from Movement Wallet Adapter"],
      };
    } else {
      // We are on Devnet, so just use a simple transfer transaction as the derived account can fund their own account with APT.
      transactionData = {
        function: "0x1::aptos_account::transfer",
        functionArguments: [account.address, 717],
      };
    }

    setGlobalTransactionInProgress(true);
    try {
      const transactionInput: InputTransactionData = {
        data: transactionData,
        options: {
          maxGasAmount: 2000,
        },
        sender: account.address,
      };

      // If is testnet, and is not a native aptos wallet,we use gas station to sponsor the transaction
      if (!wallet.isMovementNativeWallet && dappNetwork === Network.TESTNET) {
        transactionInput.transactionSubmitter = getTransactionSubmitter();
      }

      const txn = await signAndSubmitTransaction(transactionInput);

      await movementClient(network).waitForTransaction({
        transactionHash: txn.hash,
      });

      toast({
        title: "Success",
        description: <TransactionHash hash={txn.hash} network={network} />,
      });

      void aptBalance.refetch();
    } catch (error) {
      console.log(`Error signing and submitting transaction: ${error}`);
      toast({
        title: "Error",
        description: `${error}`,
      });
    } finally {
      setGlobalTransactionInProgress(false);
    }
  };

  return (
    <Card>
      <CardHeader>
        <CardTitle>Actions</CardTitle>
      </CardHeader>
      <CardContent className="flex flex-wrap gap-4">
        <Button
          onClick={onSignTransaction}
          disabled={!sendable || globalTransactionInProgress}
        >
          Sign transaction
        </Button>
        <Button
          onClick={onSignMessage}
          disabled={!sendable || globalTransactionInProgress}
        >
          Sign message
        </Button>
        <Button
          onClick={onSignMessageAndVerify}
          disabled={!sendable || globalTransactionInProgress}
        >
          Sign message and verify
        </Button>
        <Button
          onClick={onSignAndSubmitTransaction}
          disabled={!sendable || globalTransactionInProgress}
        >
          Sign and submit transaction
        </Button>
      </CardContent>
    </Card>
  );
}
